#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpackage remove rsa"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # @TODO
}

run() {
  core $@
}

run $@
